name: superglue
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - flask=3.0.3
  - flask-cors=5.0.0
  - pandas=2.0.3
  - numpy=1.24.3
  - rdkit=2024.3.5
  - pip
  - pip:
      - flask
      - flask-cors